### ISSUE TITLE
Failed to execute script pyi_rth_qt5plugins

### ISSUE THREAD

**Issue by MileageMilestone** [RiotGames/leaguedirector#18]
Hey folks,

First of all, amazing tool! I start making a production for a video, but then...
reinstalled my OS and League Editor and cannot launched it again. I run to the following message:

**Fatal error detected**: "_Failed to execute script pyi_rth_qt5plugins_"

A little help will be really appreciated.

Thanks,
Mileage

**Comment by alangareis** [comment]
i have the same problem

**Comment by Outtcha** [comment]
same bug of (Failed to execute script pyi_rth_qt5plugins) what i can do

**Comment by cammm** [comment]
There will be an update in a few days which should resolve this or at least help us know what it is.

**Comment by leslee93** [comment]
and where can we download this patch?

**Comment by Doom2Tank** [comment]
when the update will come and how we are going to download it ?

**Comment by cammm** [comment]
Can you try running the latest version 0.1.1 and let me know if it still crashes. If it does, then send me the log file from your (USER)/Documents/LeagueDirector/logs/

https://github.com/RiotGames/leaguedirector/releases/latest

**Comment by MileageMilestone** [comment]
Hey @cammm,

Thank you for sharing and for all efforts to solve this issue!

I did install the new version of League Director, however the issue still occurs during launch. 

The location of the installation:

[![Image from Gyazo](https://i.gyazo.com/83615e74205b7f0c83c064f5f6e94122.png)](https://gyazo.com/83615e74205b7f0c83c064f5f6e94122)


As for the Logs that should be created once launched, there was no folder created for League Director:

[![Image from Gyazo](https://i.gyazo.com/36e0aa0cc0940725807bc1a5fc488262.png)](https://gyazo.com/36e0aa0cc0940725807bc1a5fc488262)

Please let me know if there is additional information that you may need, or if something else I'm missing.

Thank you,
Mileage

**Comment by cammm** [comment]
Ok thanks for this information. Are you able to jump on discord to help diagnose this a little faster?

https://discord.gg/7j5fdRp

**Comment by leslee93** [comment]
so any updates about the error?

**Comment by cammm** [comment]
Can you open a new windows command line (Start -> Run -> cmd) and enter this and show me what it returns?

`echo %PROCESSOR_ARCHITECTURE%`

**Comment by MileageMilestone** [comment]
Hello,

Posting it here also to have track of it: 


[![Image from Gyazo](https://i.gyazo.com/3e1b633477aa74567e12d09462a22c8f.png)](https://gyazo.com/3e1b633477aa74567e12d09462a22c8f)


Best,
Mileage

**Comment by DanielJStevens** [comment]
I wanted to add to this.

I used League Director fine previously but after refreshing my PC (basically reinstalling Windows) I had to reinstall and now get this error.

I'm wondering if it's a missing dependency causing the issue?

**Comment by DanielJStevens** [comment]
Okay, installed Visual Studio, attempted to run and still got the issue.

Installed "Game Development With C++" and it opened fine now.

I'll try uninstall some of the new stuff and see which one is required.

Can possibly add the required redistributable to the base installation?

**Comment by MileageMilestone** [comment]
Hello @DanielJStevens ,

Thank you for the suggestion. Unfortunately, at my end I'm with Python 3.7.3 already installed and Visual Studio also - still getting stuck during launch.

Thanks for the input do!

Best,
Mileage

**Comment by emirkanacar** [comment]
I got same error.
I am installed Qt last version and fixed.
https://www.qt.io/download-thank-you

**Comment by Doom2Tank** [comment]
dear @cammm 
i used the cmd and still nothing here is a full photo for the details note : the cmd gave me another answer
![help](https://user-images.githubusercontent.com/48347896/55635538-3d48da00-57c1-11e9-9298-565b45c28163.PNG)

**Comment by MileageMilestone** [comment]
Hello @emirkanacar,

Thanks for the advise. Indeed QT  move me to another error:

[![Image from Gyazo](https://i.gyazo.com/55654476a9d11e48c8e59807b235251b.png)](https://gyazo.com/55654476a9d11e48c8e59807b235251b)

From there I re-downloaded Visual C++ Redistributable Packages for Visual Studio 2013 (MS link: https://bit.ly/2eHGhS9) and the League Editor start working!!!

The weird thing that I didn't consider was that I did already had the x64 version, but it appears that I need it also the x86 also. 

[![Image from Gyazo](https://i.gyazo.com/cd90dc3f430c6ff26d62c64f5c33aa20.png)](https://gyazo.com/cd90dc3f430c6ff26d62c64f5c33aa20)

Someone more knowledgeable may know why.

Thank you all again! 

I'll mark this issue as resolved in a few day to check if everything will be working till then!

Best regards,
Mileage

**Comment by MileageMilestone** [comment]
Forgot to mention:

Now the Editor also create logs in (USER)/Documents/LeagueDirector/logs/

Pinning them below for @cammm, since he may want to check on them:

[logs.zip](https://github.com/RiotGames/leaguedirector/files/3051404/logs.zip)

Best,
Mileage

**Comment by Doom2Tank** [comment]
dear @emirkanacar and @MileageMilestone 
How i can use Qt i dont know how to use it ?
please help

**Comment by MileageMilestone** [comment]
Hello @Doom2Tank,

As far I can tell, you don't need to use it. You need to installed from the link that @emirkanacar  provided (paste it here again: https://www.qt.io/download-thank-you) and launched it once. 

From there you just install League Editor and see if there is anything different from "_Failed to execute script pyi_rth_qt5plugins_".

Hope this helps,
Mileage

**Comment by Doom2Tank** [comment]
mister @MileageMilestone 
for the record it worked BUT I HAVE TO UNINSTALL AND INSTALL THE DIRECTOR EVERY SINGLE TIME JUST TO USE IT ONCE !!

*srry cause the caps* anyway after i play the director for a while it stopped working 
so the message appears again and i am stuck in a loop
I'm not in a hurry or asking for help I'm only munitioning it to the public though i have qt and not python 

Thanks for help @MileageMilestone 
from the shadows of the isles 
Doom

**Comment by MileageMilestone** [comment]
Hello @Doom2Tank,

Well that seems quite interesting, thank you for sharing it! As you know every setup/ environment works differently, so in my case QT and Python installations seems to do the trick.

I also share your concern, but on a different angle: that a 41 GB installation of QT for 298 Mb client it's a bit of on overkill, but still I'm quite happy that I can move to Video Production.

My wild guess, as you may already know it, is to follow this topic issue build and try installing Python in the meantime and see if there is any change to League Director.

By all means, if you aren't in the rush you can wait for someone more knowledgeable to share wisdom or/if an update for the League Director update comes out, since the proposed from above is more or less a temporary workaround.

In addition,  check if League Director is creating Logs in (USER)/Documents/LeagueDirector/logs/ that you can upload.

Hope this helps out,
Mileage

**Comment by cammm** [comment]
Sorry for the long delay in fixing this problem, the next release of League Director will have it fixed but in the meantime just install this from Microsoft and you should be good to go.

https://aka.ms/vs/15/release/vc_redist.x86.exe
